apiVersion: v1
kind: Service
metadata:
  name: jupyter
  namespace: default
  labels:
    app: jupyter
spec:
  ports:
  - port: 8888
    name: http
    targetPort: 80
  selector:
    app: jupyter
  type: LoadBalancer