version: '2'
services:
  zookeeper:
    image: netflixoss/exhibitor:1.5.2
    # ports: 
    #   - "2181:2181"
    network_mode: 'host'
    command: "--port 8081"

  mesos1:
    image: mesosphere/mesos-master:1.1.01.1.0-2.0.107.ubuntu1404
    # ports:
    #   - "5050:5050"
    network_mode: 'host'
    environment:
      - MESOS_PORT=5050
      - MESOS_ZK=zk://127.0.0.1:2181/mesos
      - MESOS_QUORUM=1
      - MESOS_REGISTRY=in_memory
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/lib/mesos
#      MESOS_LIBPROCESS_ADVERTISE_IP=192.168.99.100

  marathon:
    image: mesosphere/marathon:v0.8.1
    # ports:
    #   - "8080:8080"
    network_mode: 'host'
    command: "--master zk://127.0.0.1:2181/mesos --zk zk://127.0.0.1:2181/marathon --task_launch_timeout 300000"

  slave1:
    image: mesosphere/mesos-slave:1.1.01.1.0-2.0.107.ubuntu1404
    network_mode: 'host'
    privileged: true
    pid: "host"
    environment:
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_DOCKER_STOP_TIMEOUT=2mins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /cgroup:/cgroup
      - /usr/local/bin/docker:/usr/local/bin/docker

  slave2:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    network_mode: 'host'
    privileged: true
    pid: "host"
    environment:
      - MESOS_PORT=5052
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_DOCKER_STOP_TIMEOUT=2mins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /cgroup:/cgroup
      - /usr/local/bin/docker:/usr/local/bin/docker

  slave3:
    image: mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404
    network_mode: 'host'
    privileged: true
    pid: "host"
    environment:
      - MESOS_PORT=5053
      - MESOS_MASTER=zk://127.0.0.1:2181/mesos
      - MESOS_SWITCH_USER=0
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_LOG_DIR=/var/log/mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
      - MESOS_EXECUTOR_REGISTRATION_TIMEOUT=5mins
      - MESOS_DOCKER_STOP_TIMEOUT=2mins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /cgroup:/cgroup
      - /usr/local/bin/docker:/usr/local/bin/docker

